name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - ".github/**"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements-test.txt

      - name: pre-commit
        uses: pre-commit/action@v3.0.0

      - name: mypy
        run: mypy .
